# **EVALUATION**

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
# from PIL import Image
# import os

# def resize_images(folder_path, output_size=(256, 256)):
#     image_names = [file for file in os.listdir(folder_path) if file.lower().endswith(('.png', '.jpg', '.jpeg', '.gif'))]

#     for image_name in image_names:
#         image_path = os.path.join(folder_path, image_name)
#         image = Image.open(image_path)
#         resized_image = image.resize(output_size)
#         resized_image.save(image_path)

# # Replace this path with your actual image folder path
# folder_path = '/content/drive/MyDrive/TestDataAndResults/MeGlass/noglasses/gallery'
# resize_images(folder_path)


In [ ]:
# from PIL import Image
# import os

# def resize_images(folder_path, folder_path2, output_size=(120, 120)):
#     image_names = [file for file in os.listdir(folder_path) if file.lower().endswith(('.png', '.jpg', '.jpeg', '.gif'))]

#     for image_name in image_names:
#         image_path1 = os.path.join(folder_path1, image_name)
#         image_path2 = os.path.join(folder_path2, image_name)
#         image = Image.open(image_path1)
#         resized_image = image.resize(output_size)
#         resized_image.save(image_path2)

# # Replace this path with your actual image folder path
# folder_path1 = '/content/drive/MyDrive/TestDataAndResults/MeGlass/with_glasses/probe'
# folder_path2 = '/content/drive/MyDrive/TestDataAndResults/MeGlass/with_glasses/probe120*120'
# resize_images(folder_path1, folder_path2)

**GO TO MAIN FOLDER PATH**

In [ ]:
root_path = '/content/drive/MyDrive/'

In [ ]:
!pip install facenet-pytorch

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.9/1.9 MB 9.3 MB/s eta 0:00:00


In [ ]:
import os
import numpy as np
import torch
import torchvision.transforms as transforms
from sklearn.metrics import roc_curve, accuracy_score
from PIL import Image
import matplotlib.pyplot as plt
from facenet_pytorch import MTCNN, InceptionResnetV1

from sklearn.metrics import confusion_matrix
from sklearn.metrics import precision_score, recall_score, f1_score

import random
from PIL import Image, ImageEnhance, ImageOps

In [ ]:
def augment_and_save(input_folder, output_folder):
    # Create output folder if it doesn't exist
    if not os.path.exists(output_folder):
        os.makedirs(output_folder)

    files = os.listdir(input_folder)
    for file_name in files:
        if file_name.lower().endswith(('.png', '.jpg', '.jpeg', '.gif', '.bmp')):
            if not file_name.endswith('mask.png'):

              input_path = os.path.join(input_folder, file_name)
              image = Image.open(input_path)

              # Original flipped image
              save_image(output_folder, file_name, image, '_orig')

              # Original flipped image
              flipped_image = image.transpose(Image.FLIP_LEFT_RIGHT)
              save_image(output_folder, file_name, flipped_image, '_flipped')

def save_image(output_folder, original_name, augmented_image, suffix):
    output_file_name = os.path.splitext(original_name)[0] + suffix + os.path.splitext(original_name)[1]
    output_path = os.path.join(output_folder, output_file_name)
    augmented_image.save(output_path)

In [ ]:
input_folder = root_path + rf'/TestDataAndResults/MeGlass/noglasses/gallery'
output_folder = root_path + rf'/TestDataAndResults/MeGlass/JustImg/noglasses/gallery'
augment_and_save(input_folder, output_folder)

In [ ]:
input_folder = root_path + rf'/TestDataAndResults/MeGlass/removed_by_default/noglasses_probe'
output_folder = root_path + rf'/TestDataAndResults/MeGlass/JustImg/removed_by_default/noglasses_probe'
augment_and_save(input_folder, output_folder)

In [ ]:
input_folder = root_path + rf'/TestDataAndResults/MeGlass/removed_by_default/noglasses_gallery'
output_folder = root_path + rf'/TestDataAndResults/MeGlass/JustImg/removed_by_default/noglasses_gallery'
augment_and_save(input_folder, output_folder)

In [ ]:
input_folder = root_path + rf'/TestDataAndResults/MeGlass/removed_by_default/probe'
output_folder = root_path + rf'/TestDataAndResults/MeGlass/JustImg/removed_by_default/probe'
augment_and_save(input_folder, output_folder)

In [ ]:
input_folder = root_path + rf'/TestDataAndResults/MeGlass/removed_by_default/gallery'
output_folder = root_path + rf'/TestDataAndResults/MeGlass/JustImg/removed_by_default/gallery'
augment_and_save(input_folder, output_folder)

In [ ]:
input_folder = root_path + rf'/TestDataAndResults/MeGlass/removed_by_prop/gallery'
output_folder = root_path + rf'/TestDataAndResults/MeGlass/JustImg/removed_by_prop/gallery'
augment_and_save(input_folder, output_folder)

In [ ]:
input_folder = root_path + rf'/TestDataAndResults/MeGlass/removed_by_prop/probe'
output_folder = root_path + rf'/TestDataAndResults/MeGlass/JustImg/removed_by_prop/probe'
augment_and_save(input_folder, output_folder)

In [ ]:
input_folder = root_path + rf'/TestDataAndResults/MeGlass/removed_by_HiSD/probe'
output_folder = root_path + rf'/TestDataAndResults/MeGlass/JustImg/removed_by_HiSD/probe'
augment_and_save(input_folder, output_folder)

In [ ]:
input_folder = root_path + rf'/TestDataAndResults/MeGlass/removed_by_ERGAN120*120'
output_folder = root_path + rf'/TestDataAndResults/MeGlass/JustImg/removed_by_ERGAN120*120'
augment_and_save(input_folder, output_folder)

In [ ]:
input_folder = root_path + rf'/TestDataAndResults/MeGlass/removed_by_SAGAN'
output_folder = root_path + rf'/TestDataAndResults/MeGlass/JustImg/removed_by_SAGAN'
augment_and_save(input_folder, output_folder)

# **########################################################################**

In [ ]:
folder_name = 'MeGlass'

In [ ]:
import os
import numpy as np
from PIL import Image

# Path to the folder containing your images
folder_path = root_path + rf'/TestDataAndResults/{folder_name}/JustImg/noglasses/gallery'

# Initialize variables to store sum of pixel values and sum of squared pixel values
sum_channels = np.zeros(3)
sum_squares_channels = np.zeros(3)
count = 0

# Iterate over each image in the folder
for filename in os.listdir(folder_path):
    # Load the image
    image_path = os.path.join(folder_path, filename)
    img = np.array(Image.open(image_path))

    # Normalize pixel values to range [0, 1]
    img = img / 255.0

    # Add pixel values to sum
    sum_channels += np.sum(img, axis=(0, 1))
    sum_squares_channels += np.sum(np.square(img), axis=(0, 1))
    count += img.shape[0] * img.shape[1]

# Compute mean and standard deviation
mean = sum_channels / count
std = np.sqrt((sum_squares_channels / count) - np.square(mean))

print("Computed mean:", mean)
print("Computed std:", std)

Computed mean: [0.50486435 0.38405047 0.33652101]
Computed std: [0.27339437 0.23430942 0.2287626 ]


In [ ]:
import os
import numpy as np
from PIL import Image

# Path to the folder containing your images
folder_path = root_path + rf'/TestDataAndResults/{folder_name}/noglasses/probe'

# Initialize variables to store sum of pixel values and sum of squared pixel values
sum_channels = np.zeros(3)
sum_squares_channels = np.zeros(3)
count = 0

# Iterate over each image in the folder
for filename in os.listdir(folder_path):
    # Load the image
    image_path = os.path.join(folder_path, filename)
    img = np.array(Image.open(image_path))

    # Normalize pixel values to range [0, 1]
    img = img / 255.0

    # Add pixel values to sum
    sum_channels += np.sum(img, axis=(0, 1))
    sum_squares_channels += np.sum(np.square(img), axis=(0, 1))
    count += img.shape[0] * img.shape[1]

# Compute mean and standard deviation
mean = sum_channels / count
std = np.sqrt((sum_squares_channels / count) - np.square(mean))

print("Computed mean:", mean)
print("Computed std:", std)

Computed mean: [0.50248019 0.38156212 0.33352976]
Computed std: [0.27068246 0.23326414 0.22752827]


# **EVALUATE NON GLASSES IMAGES WITH REMOVED GLASSES IMAGES**

In [ ]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print('Using device:', device)
model = InceptionResnetV1(pretrained='vggface2').eval().to(device)

def extract_features(image_path):
    with torch.no_grad():
        image = Image.open(image_path)
        image_tensor = transform(image).unsqueeze(0)
        features = model(image_tensor).squeeze().numpy()
    return features

# Define the cosine similarity function
def cosine_similarity(a, b):
    dot_product = np.dot(a, b)
    norm_a = np.linalg.norm(a)
    norm_b = np.linalg.norm(b)
    similarity = dot_product / (norm_a * norm_b)
    return similarity


# Define the transforms applied to each image
transform = transforms.Compose([
    transforms.Resize(256),
    transforms.ToTensor(),
    # transforms.Normalize(mean=[0.5, 0.5, 0.5], std=[0.5, 0.5, 0.5])
    transforms.Normalize(mean=[0.5, 0.45, 0.40], std=[0.27, 0.23, 0.23]) # good
])

def cal_tar_at_far(gallery_folder, probe_folder, desired_fars):

    gallery_images_list = os.listdir(gallery_folder)
    probe_images_list = os.listdir(probe_folder)

    gallery_features = []
    probe_features = []

    for gallery_image in gallery_images_list:
        if not gallery_image.endswith('mask.png'):
            gallery_image_path = os.path.join(gallery_folder, gallery_image)
            gallery_features.append(extract_features(gallery_image_path))

    for probe_image in probe_images_list:
        if not probe_image.endswith('mask.png'):
            probe_image_path = os.path.join(probe_folder, probe_image)
            probe_features.append(extract_features(probe_image_path))

    gallery_features = np.array(gallery_features)
    probe_features = np.array(probe_features)

    similarities = np.zeros((len(probe_features), len(gallery_features)))
    for i, probe_feature in enumerate(probe_features):
        for j, gallery_feature in enumerate(gallery_features):
            similarity = cosine_similarity(probe_feature, gallery_feature)
            similarities[i, j] = similarity

    y_true = np.zeros(len(probe_images_list) * len(gallery_images_list))
    y_score = np.zeros(len(probe_images_list) * len(gallery_images_list))
    for i, probe_feature in enumerate(probe_features):
        for j, gallery_feature in enumerate(gallery_features):
            index = i * len(gallery_images_list) + j
            y_true[index] = int(gallery_images_list[j].split("@")[:2] == probe_images_list[i].split("@")[:2])
            y_score[index] = similarities[i, j]

    fpr, tpr, thresholds = roc_curve(y_true, y_score)

    # plt.title('Receiver Operating Characteristic')
    # plt.plot(fpr, tpr, 'b')
    # plt.legend(loc = 'lower right')
    # plt.plot([0, 1], [0, 1],'r--')
    # plt.xlim([0, 1])
    # plt.ylim([0, 1])
    # plt.ylabel('True Positive Rate')
    # plt.xlabel('False Positive Rate')
    # plt.show()

    for desired_far in desired_fars:
        # Find the index where FAR is closest to the desired FAR
        index = np.argmin(np.abs(fpr - desired_far))
        tar_at_desired_far = tpr[index]
        print("TAR at FAR =", desired_far, "is", tar_at_desired_far)

    # Calculate accuracy
    y_pred = (y_score >= thresholds[index]).astype(int)
    acc = accuracy_score(y_true, y_pred)
    print("Accuracy:", acc)

    return fpr, tpr, thresholds, y_true, y_score

Using device: cpu


NOTE: The number of samples should be greater than the dimension of the coding layer, here 2048 for the Inception pool 3 layer. Otherwise the covariance is not full rank resulting in complex numbers and nans by calculating the square root. (We doubled the number of test samples so that there is no computational problem due to the number of samples being less than 2048.)

In [ ]:
gallery_folder = root_path + rf'/TestDataAndResults/{folder_name}/JustImg/noglasses/gallery'
probe_folder = root_path + rf'/TestDataAndResults/{folder_name}/JustImg/removed_by_default/probe_double'
desired_fars = [0.1, 0.01, 0.001]
cal_tar_at_far(gallery_folder, probe_folder, desired_fars)

gallery_folder = root_path + rf'/TestDataAndResults/{folder_name}/JustImg/noglasses/gallery'
probe_folder = root_path + rf'/TestDataAndResults/{folder_name}/JustImg/removed_by_prop/probe_double'
desired_fars = [0.1, 0.01, 0.001]
cal_tar_at_far(gallery_folder, probe_folder, desired_fars)

gallery_folder = root_path + rf'/TestDataAndResults/{folder_name}/JustImg/noglasses/gallery'
probe_folder = root_path + rf'/TestDataAndResults/{folder_name}/JustImg/removed_by_HiSD/probe'
desired_far = [0.1, 0.01, 0.001]
cal_tar_at_far(gallery_folder, probe_folder, desired_far)

gallery_folder = root_path + rf'/TestDataAndResults/{folder_name}/JustImg/noglasses/gallery'
probe_folder = root_path + rf'/TestDataAndResults/{folder_name}/JustImg/removed_by_SAGAN'
desired_far = [0.1, 0.01, 0.001]
cal_tar_at_far(gallery_folder, probe_folder, desired_far)

gallery_folder = root_path + rf'/TestDataAndResults/{folder_name}/JustImg/noglasses/gallery'
probe_folder = root_path + rf'/TestDataAndResults/{folder_name}/JustImg/removed_by_ERGAN120*120'
desired_far = [0.1, 0.01, 0.001]
cal_tar_at_far(gallery_folder, probe_folder, desired_far)

TAR at FAR = 0.1 is 0.8109649122807018
TAR at FAR = 0.01 is 0.48026315789473684
TAR at FAR = 0.001 is 0.197953216374269
Accuracy: 0.998529205567525
TAR at FAR = 0.1 is 0.8162280701754386
TAR at FAR = 0.01 is 0.4855263157894737
TAR at FAR = 0.001 is 0.20584795321637428
Accuracy: 0.9985365582572415
TAR at FAR = 0.1 is 0.7940058479532164
TAR at FAR = 0.01 is 0.44883040935672514
TAR at FAR = 0.001 is 0.18771929824561404
Accuracy: 0.9985255292226668
TAR at FAR = 0.1 is 0.797953216374269
TAR at FAR = 0.01 is 0.4359649122807018
TAR at FAR = 0.001 is 0.17207602339181285
Accuracy: 0.9985162101159331
TAR at FAR = 0.1 is 0.7653508771929824
TAR at FAR = 0.01 is 0.4004385964912281
TAR at FAR = 0.001 is 0.13742690058479531
Accuracy: 0.9984957764782326


(array([0.00000000e+00, 8.55464192e-08, 4.79059948e-06, ...,
        9.99865350e-01, 9.99865521e-01, 1.00000000e+00]),
 array([0., 0., 0., ..., 1., 1., 1.]),
 array([ 1.97876036,  0.97876036,  0.94657981, ..., -0.33424327,
        -0.33427191, -0.54241878]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([ 0.14511348,  0.27758539, -0.00410961, ...,  0.38166353,
         0.49013487,  0.47005677]))

# **With glasses compared to No glasses**

In [ ]:
gallery_folder = root_path + rf'/TestDataAndResults/MeGlass/noglasses/gallery'
probe_folder = root_path + rf'/TestDataAndResults/MeGlass/with_glasses/probe'
desired_fars = [0.1, 0.01, 0.001]
cal_tar_at_far(gallery_folder, probe_folder, desired_fars)

TAR at FAR = 0.1 is 0.787719298245614
TAR at FAR = 0.01 is 0.4450292397660819
TAR at FAR = 0.001 is 0.16900584795321638
Accuracy: 0.9985113368215861


(array([0.00000000e+00, 3.42185677e-07, 1.16343130e-05, ...,
        9.99807692e-01, 9.99808376e-01, 1.00000000e+00]),
 array([0., 0., 0., ..., 1., 1., 1.]),
 array([ 1.9769026 ,  0.9769026 ,  0.91285622, ..., -0.33472452,
        -0.33474579, -0.54516065]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0.22652635, 0.29227749, 0.33574682, ..., 0.06917893, 0.11108194,
        0.31433225]))

# **No glasses compared to No glasses**

In [ ]:
gallery_folder = root_path + rf'/TestDataAndResults/MeGlass/noglasses/gallery'
probe_folder = root_path + rf'/TestDataAndResults/MeGlass/noglasses/probe'
desired_fars = [0.1, 0.01, 0.001]
cal_tar_at_far(gallery_folder, probe_folder, desired_fars)

TAR at FAR = 0.1 is 0.8748538011695907
TAR at FAR = 0.01 is 0.6672514619883041
TAR at FAR = 0.001 is 0.408187134502924
Accuracy: 0.9986488150200061


(array([0.        , 0.        , 0.        , ..., 0.99933753, 0.99933821,
        1.        ]),
 array([0.00000000e+00, 5.84795322e-04, 2.92397661e-03, ...,
        1.00000000e+00, 1.00000000e+00, 1.00000000e+00]),
 array([ 2.00000012,  1.00000012,  1.        , ..., -0.28285345,
        -0.28285652, -0.50200248]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0.17706013, 0.25648686, 0.22803931, ..., 0.19748661, 0.30406541,
        0.30393621]))